#
# Config for continual meta-test of Classifier-Basline models on Omniglot. Fine-tunes just the classifier.
#

# Dataset
dataset: omni
train_examples: 15
test_examples: 5

# Test Method
eval_method: iid
reinit_params: classifier.linear
opt_params: all
classes: 600
lr: 0.0055
