#
# Config for continual meta-test of OML-like models on Omniglot. Fine-tunes the last two layers.
#

# Dataset
dataset: omni
im_size: 84
train_examples: 15
test_examples: 5

# Test Method
reinit_params: pn.2
opt_params: pn
classes: 600
lr: !include learning-rates.yml
