#
# Config for a model which is equivalent to OML, but built using Classifier.
#

# Dataset
dataset: omni
train_size: 20
im_size: 84

# Training Configuration
batch_size: 1
num_batches: 20
train_cycles: 1
val_size: 0
remember_size: 64
remember_only: false
inner_lr: 0.03
outer_lr: 0.0001

epochs: 25000
seed: 1

# Model Architecture
model: classifier
model_args:
  encoder: convnet
  encoder_args:
    num_blocks: 6
    num_filters: 256
    stride: [2, 1, 2, 1, 2, 2]
    padding: 0
    norm_type: null
    pool_size: null
  classifier: mlp-classifier
  classifier_args: {num_classes: 1000, hidden_layers: 1024}

# Optimization Configuration
inner_params: classifier
outer_params: all
output_layer: classifier.mlp.2

eval_steps: [10000, 25000]
eval:
  - 1ft: !include eval-sweep-omni-84-1layer.yml
  - 2ft: !include eval-sweep-omni-84-2layer.yml
  - ft-all: !include eval-sweep-omni-84-unfrozen.yml
  - iid-1ft: !include eval-sweep-omni-84-iid-1layer.yml
  - iid-ft-all: !include eval-sweep-omni-84-iid-unfrozen.yml
